version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_projetoaula03
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: projetoaula03
      POSTGRES_USER: usuariocoti
      POSTGRES_PASSWORD: coti2025
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: